// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ktJobs.Api.Data;

#nullable disable

namespace ktJobs.Api.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20260329145955_InitialCreateWithTypoFix")]
    partial class InitialCreateWithTypoFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ktJobs.Api.Domain.JobListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollectedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Company = "TechStream Solutions",
                            Description = "A great opportunity to start your backend career in a supportive team environment.",
                            IsRemote = true,
                            Location = "Remote",
                            PostedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salary = "£35,000 - £45,000",
                            Source = "LinkedIn",
                            SourceJobId = "LI-001",
                            Status = 0,
                            Title = "Junior Backend Developer",
                            Url = "https://www.linkedin.com"
                        },
                        new
                        {
                            Id = 2,
                            CollectedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Company = "BrightBox Media",
                            Description = "Looking for a developer to bridge the gap between our React frontend and C# API.",
                            IsRemote = false,
                            Location = "London",
                            PostedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salary = "£50,000",
                            Source = "Indeed",
                            SourceJobId = "IND-002",
                            Status = 1,
                            Title = "Full Stack Engineer",
                            Url = "https://www.indeed.com"
                        },
                        new
                        {
                            Id = 3,
                            CollectedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Company = "Global Logistics",
                            Description = "Focus on building robust middleware and third-party API integrations for our logistics platform.",
                            IsRemote = false,
                            Location = "Manchester",
                            PostedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salary = "Competitive",
                            Source = "Reed",
                            SourceJobId = "RE-003",
                            Status = 0,
                            Title = "API Integration Specialist",
                            Url = "https://www.reed.co.uk"
                        },
                        new
                        {
                            Id = 4,
                            CollectedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Company = "StartUp Inc",
                            Description = "We value transferable skills. Perfect first role for someone moving from IT support into development.",
                            IsRemote = true,
                            Location = "Birmingham",
                            PostedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salary = "£32,000",
                            Source = "Glassdoor",
                            SourceJobId = "GD-004",
                            Status = 3,
                            Title = "Junior Software Engineer",
                            Url = "https://www.glassdoor.com"
                        },
                        new
                        {
                            Id = 5,
                            CollectedDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Company = "FinTech Collective",
                            Description = "Deep dive into .NET 8 and high-performance financial data processing.",
                            IsRemote = true,
                            Location = "Remote",
                            PostedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Salary = "£60,000",
                            Source = "Totaljobs",
                            SourceJobId = "TJ-005",
                            Status = 2,
                            Title = ".NET Backend Developer",
                            Url = "https://www.totaljobs.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
